import { IGrad } from '../app/grad';

export let gradovi: IGrad[] = [
  {
    name: 'Skopje',
    type: 'city',
    lat: 41.9981,
    lon: 21.4254,
    img: 'https://i.imgur.com/aVttGhY.jpg',
    bgImage:
      'https://i.imgur.com/dFdtIp5.jpg',
    desc: 'With all of its perfections and flaws, Skopje is a city like no other. We grew up here, we live here, we work here.. All of our memories with the people we care the most about are created on the streets of Skopje. We are proud of the city with inexhaustible energy. The city that almost never sleeps. The wonderful squares, the biggest monument on the Balkan Peninsula, the City Park, Vodno and Matka, the Vrelo caves, the way Vardar cuts it in half, the Millenium cross, the Old town bazaar, the Kale fortress .. all of these represent a certain period and tell a different story of the capital city of the land of the sun.',

    sights: [
      'Old Bazaar',
      'Matka Canyon',
      'Skopje Fortress',
      'Millenium Cross',
    ],
    accommodation: [
      'Doubletree Hilton',
      'Marriott Hotel',
      'Hotel City Park',
      'Hotel Karpos',
    ],
  },
  {
    name: 'Bitola',
    type: 'city',
    lat: 41.0297,
    lon: 21.3292,
    img: 'https://i.imgur.com/PAUo0zb.jpg',
    bgImage:
      'https://i.imgur.com/VtdAHof.jpg',
    desc: 'Bitola offers you absolute zero stress and a spirit of well-being. This is a warm invite to feel the mixture of the East and the West, to reinvent your term of taste due to the culinary delights that city restaurants offer, and to be part of a very typical and vibrant local lifestyle.',

    sights: ['Saat Kula', 'Shirok Sokak'],
    accommodation: ['Bela Kukja Hotel', 'Hotel Threatre', 'Somnia'],
  },
  {
    name: 'Ohrid',
    type: 'city',
    lat: 41.1231,
    lon: 20.8016,
    img: 'https://i.imgur.com/EKyphPr.jpg',
    bgImage:
      'https://i.imgur.com/7WRU8ix.png',
    desc: `Sublime Ohrid is North Macedonia's most seductive destination. It sits on the edge of serene Lake Ohrid, with an atmospheric old quarter that cascades down steep streets, dotted with beautiful churches and topped by the bones of a medieval castle. Traditional restaurants and lakeside cafes liven up the cobblestone streets, which in high summer can be very lively indeed.`,
    sights: ['Saint Sophia', 'Ancient theatre', 'Bay of Bones'],
    accommodation: ['Inex Olgica'],
  },
  {
    name: 'Saint Sophia',
    type: 'sight',
    img: 'https://i.imgur.com/e3d44k8.jpg',
    desc: 'The Church of Saint Sophia is a church in Ohrid, North Macedonia. The church is one of the most important monuments of North Macedonia, housing architecture and art from the Middle Ages.',
  },
  {
    name: 'Ancient theatre',
    type: 'sight',
    img: 'https://i.imgur.com/5qEYwSJ.jpg',
    desc: 'The Ancient theatre of Ohrid of the Hellenistic period is located in Ohrid, North Macedonia. It was built in 200 BC and is the only Hellenistic-type theatre in the country as the other three in Scupi, Stobi and Heraklea Lynkestis are from Roman times',
  },
  {
    name: 'Bay of Bones',
    type: 'sight',
    img: 'https://i.imgur.com/j9Pkpw9.jpg',
    desc: 'Replica of ancient lakeside settlement',
  },
  {
    name: 'Inex Olgica',
    type: 'accommodation',
    img: 'https://i.imgur.com/XOlE15H.jpg',
    desc: 'Inex Olgica Hotel & SPA is situated on the shore of the Ohrid Lake, 4 km away from Ohrid and a 10-minute drive from Ohrid Airport. Guests benefit from the free WiFi and free parking on site.',
    link: 'https://www.booking.com/hotel/mk/inex-gorica.en-gb.html?aid=304142&label=gen173nr-1FCAEoggI46AdIM1gEaJMBiAEBmAEJuAEHyAEM2AEB6AEB-AEMiAIBqAIDuAKcxaygBsACAdICJDNhOWE4YjBlLWJjN2MtNDM3My04YzkzLWYzODQ3OTQ1YjE3MNgCBuACAQ&sid=ca3ee2eae1c4545cc9254e08a510e7cf&dest_id=-90608&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=1&hpos=1&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=class&srepoch=1678453623&srpvid=b1405c35dfb400f7&type=total&ucfs=1&activeTab=main',
  },
  {
    name: 'Mavrovo',
    type: 'city',
    lat: 41.6549,
    lon: 20.7339,
    img: 'https://i.imgur.com/0x3OCnO.jpg',
    bgImage: 'https://i.imgur.com/4ECqM6C.jpg',
    desc: `Discovering the beauties of nature and exploring impeccable scenery, Macedonian customs, and traditional cuisine, you find yourself in Mavrovo .Set in the breathtaking scenery, amid grassy plateaus and snowy peaks of the mountainous region of western Macedonia, it is the frosting of the cake called the Macedonian outdoor experience.`,
    sights: ["Bigorski Monastery", "St Nicholas"],
    accommodation: ["Hotel Makpetrol", "Hotel Bistra", "Hotel Radika"]
  },
  {
    name: 'Bigorski Monastery',
    type: 'sight',
    img: 'https://i.imgur.com/BEhg5ng.jpg',
    desc: 'The Monastery of Saint Jovan Bigorski is a Macedonian Orthodox monastery located in the western part of North Macedonia, near the road connecting the towns of Debar and Gostivar. The monastery church is dedicated to St. John the Baptist.',
},
{
  name: 'St Nicholas',
  type: 'sight',
  img: 'https://i.imgur.com/RO20VGR.jpg',
  desc: `St Nicholas is the former main village church of the village Mavrovo, which today is mainly submerged in the waters of the Mavrovo Lake. It was built in 1850. In 1953, with the construction of the hydro system "Mavrovo" and Mavrovo Lake, the church was under water. More recently, in periods of drought, the church is located on dry land and it can be visited.`
},
{
  name: 'Hotel Radika',
  type: 'accommodation',
  img: 'https://i.imgur.com/hYNAjBu.jpg',
  desc: `A mountain resort in Mavrovo National Park in Western Macedonia, 9 km from the Mavrovo Ski Resort, Hotel Radika enjoys a scenic location surrounded by pristine forests and just above Mavrovo Lake. The spacious rooms at the Radika Hotel come in a modern or Baroque style. They feature a digital TV with over 80 channels, a minibar, air conditioning, and a bathroom. Free WiFi is available in all areas.`,
  link: 'https://www.booking.com/Share-W3vj8kN',
},
{
  name: 'Hotel Bistra',
  type: 'accommodation',
  img: 'https://i.imgur.com/0x3OCnO.jpg',
  desc: `Hotel Bistra, Resort Mavrovo is located in National Park Mavrovo, at the foot of the Bistra Mountain and features an indoor swimming pool, fitness centre and sauna. All rooms at Hotel Bistra, Resort Mavrovo include a private bathroom, satellite TV, free Wi-Fi. Some have spa baths and a balcony with mountain views.`,
  link: 'https://www.booking.com/Share-V48ACB',
},
{
  name: 'Hotel Makpetrol',
  type: 'accommodation',
  img: 'https://i.imgur.com/JayX8EY.jpg',
  desc: 'Dotted with restaurants and bars, about a 12-minute stroll from Ski Lift "Plavi", this 3-star Hotel Makpetrol Mavrovo comprises 42 rooms. Boasting snow skiing, hiking and horse riding together with an aperitif bar, the hotel is located near Ski Mavrovo.',
  link: 'http://hotels.makpetrol.com.mk/',
},
  {
    name: 'Dojran',
    type: 'city',
    lat: 41.1811,
    lon: 22.7227,
    img: 'https://i.imgur.com/ADFvyoO.jpg',
    bgImage:
      'https://i.imgur.com/dzgGfAh.jpg',
    desc: 'Dojran was a city on the west shore of Lake Dojran in the southeast part of North Macedonia. Today, it is a collective name for two villages on the territory of the ruined city: Nov Dojran and Star Dojran, which contains both old ruins and recent construction, especially hotels, resorts, and restaurants.',
  },
  {
    name: 'Prespa',
    type: 'city',
    lat: 40.8833,
    lon: 21.0222,
    img: 'https://i.imgur.com/UDo6Pd1.jpg',
    bgImage:
      'https://i.imgur.com/ZymklCE.jpg',
    desc: 'The Lake Prespa is located on the tripoint of North Macedonia, Albania, and Greece. It is a system of two lakes separated by an isthmus: the Great Prespa Lake, divided between the three countries, and the Little Prespa Lake, mostly within Greece.',
  },
  {
    name: 'Old Bazaar',
    type: 'sight',
    img: 'https://i.imgur.com/D2efYy8.jpg',
    desc: 'In Skopje, the Old Skopje Bazaar is over the Stone Bridge on the left side of Vardar. This is a part of the city with various and rich history, tradition, culture and architecture, nowadays there has been made a connection between the old and new, economy and trade, culture and tradition. Due to the historical, developing and time occasions, culture of organization and tradition of living there are a large number of well preserved and functional objects from Ottoman period also new built objects as a feature of the modern period in the Old Skopje Bazaar.',
  },
  {
    name: 'Matka Canyon',
    type: 'sight',
    img: 'https://i.imgur.com/siTaORw.jpg',
    desc: 'If the exceptional beauty of Matka Canyon is not enough for you there are a few more reasons to visit the place. This is one of the most popular recreational areas near Skopje, attracting both locals and visitors all year long. You can do here numerous activities, like hiking, fishing or kayaking. You can also find some old monasteries in the area.',
  },
  {
    name: 'Skopje Fortress',
    type: 'sight',
    img: 'https://i.imgur.com/5RxX2QZ.jpg',
    desc: 'Kale fortress has the dominant place in Skopje. It was built of stone blocks from the ruins of the city of Scupi, during the rule of the Byzantium Emperor Justinijan the 1st.',
  },
  {
    name: 'Millenium Cross',
    type: 'sight',
    img: 'https://i.imgur.com/kVDdwKF.jpg',
    desc: 'The Millennium Cross in Skopje is a must-see attraction for anyone visiting the city. Standing tall at 66 meters, the cross is located on top of Vodno Mountain and offers panoramic views of the city and the surrounding area.',
  },
  {
    name: 'Doubletree Hilton',
    type: 'accommodation',
    img: 'https://i.imgur.com/HDa58Fb.jpg',
    desc: 'Located along the river Vardar, DoubleTree by Hilton Skopje offers 5-star accommodations within a 10 minute drive of the city center, featuring luxuriously furnished rooms and suites, large indoor swimming pool with fitness and spa and an elegant roof bar with a relaxing view.',
    link: 'https://www.booking.com/hotel/mk/doubletree-by-hilton-skopje.html',
  },
  {
    name: 'Marriott Hotel',
    type: 'accommodation',
    img: 'https://i.imgur.com/zAT7lKg.jpg',
    desc: 'Skopje Marriot Hotel is set in Skopje, 100 m from Macedonia Square and 200 from Stone Bridge. The hotel offers a spa center with an indoor pool and facilities such as hot tub, massage and steam room.',
    link: 'https://www.booking.com/hotel/mk/skopje-marriott.en-gb.html',
  },
  {
    name: 'Hotel City Park',
    type: 'accommodation',
    img: 'https://i.imgur.com/kVqr9yl.jpg',
    desc: 'Located next to the famous "Debar Maalo" area full of life and traditional restaurants, 150 m for the National Football Arena and next to the Governor of Skopje offices, the stylish City Park Hotel offers you elegant rooms with park views.',
  },
  {
    name: 'Hotel Karpos',
    type: 'accommodation',
    img: 'https://i.imgur.com/cF1d3jl.jpg',
    desc: 'Hotel Karpos is a four-star hotel with 59 spacious rooms and suites. All rooms have self control air conditioning, direct telephone line, internet access, fire protection system, mini bar, coffee/tea facilities, satellite TV, bath and hairdryer. The hotel has restaurant, two conference rooms, fitness center/sauna and underground parking garage.',
  },
  {
    name: 'Saat Kula',
    type: 'sight',
    img: 'https://i.imgur.com/sLfnDzB.jpg',
    desc: 'The Clock Tower of Bitola, known as Saat Kula, is a clock tower and one of the landmarks of the Macedonian city of Bitola. The clock tower in Bitola is a very practical monument aiding people with the time of day.',
  },
  {
    name: 'Shirok Sokak',
    type: 'sight',
    img: 'https://i.imgur.com/FOdUgY6.jpg',
    desc: 'Širok Sokak is a long pedestrian street in Bitola, North Macedonia. The street is considered to be the centre of Bitola. It roughly starts at Magnolia Square and ends in the City Park. It is graced with neo-classical buildings that contain stores, cafés and restaurants.',
  },
  {
    name: 'Bela Kukja Hotel',
    type: 'accommodation',
    img: 'https://i.imgur.com/FroKd4q.jpg',
    desc: 'Situated in Bitola, 300 m from the Main Square, Bela Kuka Hotel offers free WiFi, free air conditioning and a garden. A bus stop is 120 m away, while Shirok Sokak street with its many cafes and shops is 30 m away.',
    link: 'https://www.booking.com/hotel/mk/bela-kuka.en-gb.html?aid=304142&label=gen173nr-1FCAEoggI46AdIM1gEaJMBiAEBmAEJuAEHyAEM2AEB6AEB-AEMiAIBqAIDuAKcxaygBsACAdICJDNhOWE4YjBlLWJjN2MtNDM3My04YzkzLWYzODQ3OTQ1YjE3MNgCBuACAQ&sid=ca3ee2eae1c4545cc9254e08a510e7cf&dest_id=-75269&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=2&hpos=2&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1678451365&srpvid=a6f157d2fca9005d&type=total&ucfs=1&activeTab=main',
  },
  {
    name: 'Hotel Threatre',
    type: 'accommodation',
    img: 'https://i.imgur.com/Z95KF01.jpg',
    desc: 'Centrally located in Bitola, in a quiet residential area, Hotel Theatre offers air-conditioned rooms with free WiFi. Free public parking is available on site and free private parking can be found 50 m away from the property.',
    link: 'https://www.booking.com/hotel/mk/teatar.en-gb.html?aid=304142&label=gen173nr-1FCAEoggI46AdIM1gEaJMBiAEBmAEJuAEHyAEM2AEB6AEB-AEMiAIBqAIDuAKcxaygBsACAdICJDNhOWE4YjBlLWJjN2MtNDM3My04YzkzLWYzODQ3OTQ1YjE3MNgCBuACAQ&sid=ca3ee2eae1c4545cc9254e08a510e7cf&dest_id=-75269&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=5&hpos=5&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1678451365&srpvid=a6f157d2fca9005d&type=total&ucfs=1&activeTab=main',
  },
  {
    name: 'Somnia',
    type: 'accommodation',
    img: 'https://i.imgur.com/VOXq1YD.jpg',
    desc: 'Somnia is set in Bitola. Free WiFi is offered throughout the property.Every unit has a private bathroom and shower, air conditioning, a flat-screen TV and a fridge. Some units feature a terrace and/or a balcony with city or mountain views.',
    link: 'https://www.booking.com/hotel/mk/somnia.en-gb.html?aid=304142&label=gen173nr-1FCAEoggI46AdIM1gEaJMBiAEBmAEJuAEHyAEM2AEB6AEB-AEMiAIBqAIDuAKcxaygBsACAdICJDNhOWE4YjBlLWJjN2MtNDM3My04YzkzLWYzODQ3OTQ1YjE3MNgCBuACAQ&sid=ca3ee2eae1c4545cc9254e08a510e7cf&dest_id=-75269&dest_type=city&dist=0&group_adults=2&group_children=0&hapos=3&hpos=3&no_rooms=1&req_adults=2&req_children=0&room1=A%2CA&sb_price_type=total&sr_order=popularity&srepoch=1678452055&srpvid=76b9592b39df0114&type=total&ucfs=1&activeTab=main',
  },
  {
    name: 'Kratovo',
    type: 'city',
    lat: 42.0794,
    lon: 22.1799,
    img: 'https://i.imgur.com/o2OnOY4.jpg',
    bgImage:
      'https://i.imgur.com/yXX7rYL.jpg',
    desc: `Kratovo is a small town in North Macedonia. It is the seat of Kratovo Municipality. It lies on the western slopes of Mount Osogovo at an altitude of 600 metres above sea level. Having a mild and pleasant climate, it is located in the crater of an extinct volcano. It is known for its bridges and towers.`,
    sights: ["Clock Tower", "Kratovo Museum", "Medieval Bridge", "Kuklica"],
    accommodation: ["Hotel Kratis","Etno House"],
  },
  {
    name: 'Clock Tower',
    type: 'sight',
    img: 'https://i.imgur.com/sRS2uBb.jpg',
    desc: `The Clock Tower of Kratovo is a clock tower in the town of Kratovo, one of the six towers remaining from the town's medieval and Ottoman period. Since 2008, the tower belongs under the jurisdiction of the Museum of Kratovo.`,
  },
  {
    name: 'Kratovo Museum',
    type: 'sight',
    img: 'https://i.imgur.com/3VELCqK.jpg',
    desc: 'National Museum - Kratovo was founded in 1993 from a museum collection. The museum consists of four departments, which include: archaeological, historical, ethnological and conservation. The museum has so far implemented two permanent exhibitions, including: setting 200 ethnological objects, opened 2004 and historical setting "Kratovo through the centuries", opened in 2007.',
  },
  {
    name: 'Medieval Bridge',
    type: 'sight',
    img: 'https://i.imgur.com/DJJuiiW.jpg',
    desc: `Kratovo is featured by an old-city Macedonian architecture, it's famous for its towers and medieval stone bridges which connect the left and the right part of the city. The most famous of all is Radin Bridge (Radin Most), but also other bridges enchant with their beauty. The Bridge is over Manceva river, it's erected in 1833 on two towers, one of which is 28 meters high and other 29 meters high.`,
  },
  {
    name: 'Kuklica',
    type: 'sight',
    img: 'https://i.imgur.com/Qp33E9o.jpg',
    desc: 'Kuklica is a small village in the municipality of Kratovo, North Macedonia. It is known for the hundreds of naturally formed stone pillars that resemble humans. There are two main legends surrounding the formation of the strange stone pillars in Kuklica. The most famous legend is that of a man who could not decide which of two women he should marry. So, the man planned to marry each woman on the same day at different times. When the first wedding was in progress, the woman to marry the man second went to see who was getting married on the same day as she. When she saw her future husband marrying another woman, she cursed all in attendance at the wedding and turned them into stone.',
  },
  {
    name: 'Hotel Kratis',
    type: 'accommodation',
    img: 'https://i.imgur.com/emahA5m.jpg',
    desc: 'Centrally located in Kratovo, Hotel Kratis offers air-conditioned rooms with free WiFi. Free private parking is possible on site. Each room features a flat-screen TV with cable channels. A minibar is provided as well. Some units come with a seating area with a sofa. The en-suite bathroom is fitted with a shower and free toiletries.',
    link: 'https://www.booking.com/Share-4vQsSnw',
  },
  {
    name: 'Etno House',
    type: 'accommodation',
    img: 'https://i.imgur.com/0hzfTFw.jpg',
    desc: 'Located in Kratovo, 17 km from Aquapark Macedonia, Etno House Shancheva provides accommodation with a shared lounge, free private parking, a garden and barbecue facilities. Featuring family rooms, this property also provides guests with a terrace. The accommodation offers a 24-hour front desk.',
    link: 'https://www.booking.com/Share-PeowEk',
},

];
